/*
 * Copyright 2022 DroidconKE
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ke.droidcon.kotlin.datasource.local

import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import ke.droidcon.kotlin.datasource.local.dao.BookmarkDao
import ke.droidcon.kotlin.datasource.local.dao.FeedDao
import ke.droidcon.kotlin.datasource.local.dao.OrganizersDao
import ke.droidcon.kotlin.datasource.local.dao.SessionDao
import ke.droidcon.kotlin.datasource.local.dao.SpeakerDao
import ke.droidcon.kotlin.datasource.local.dao.SponsorsDao
import ke.droidcon.kotlin.datasource.local.model.BookmarkEntity
import ke.droidcon.kotlin.datasource.local.model.FeedEntity
import ke.droidcon.kotlin.datasource.local.model.OrganizerEntity
import ke.droidcon.kotlin.datasource.local.model.SessionEntity
import ke.droidcon.kotlin.datasource.local.model.SpeakerEntity
import ke.droidcon.kotlin.datasource.local.model.SponsorEntity
import ke.droidcon.kotlin.datasource.local.util.InstantConverter

@Database(
    entities = [
        SessionEntity::class,
        SpeakerEntity::class,
        BookmarkEntity::class,
        OrganizerEntity::class,
        SponsorEntity::class,
        FeedEntity::class,
    ],
    version = 6,
    exportSchema = true,
)
@TypeConverters(
    InstantConverter::class,
)
abstract class Database : RoomDatabase() {
    abstract fun sessionDao(): SessionDao

    abstract fun speakerDao(): SpeakerDao

    abstract fun bookmarkDao(): BookmarkDao

    abstract fun organizersDao(): OrganizersDao

    abstract fun sponsorsDao(): SponsorsDao

    abstract fun feedDao(): FeedDao

    companion object {
        val MIGRATION_4_5 =
            object : Migration(4, 5) {
                override fun migrate(db: SupportSQLiteDatabase) {
                    db.execSQL("ALTER TABLE sessions ADD COLUMN endTimeStamp INTEGER NOT NULL DEFAULT 0")
                }
            }

        /**
         * Synced tables move from an autogenerated `id` to the key sync matches on. Rows that
         * earlier syncs duplicated collapse to the most recently written one, and bookmarks
         * stored under a session's generated `id` move to its `remote_id`.
         */
        val MIGRATION_5_6 =
            object : Migration(5, 6) {
                override fun migrate(db: SupportSQLiteDatabase) {
                    db.execSQL(
                        """
                        INSERT OR IGNORE INTO bookmarks (sessionId)
                        SELECT s.remote_id FROM bookmarks b JOIN sessions s ON b.sessionId = CAST(s.id AS TEXT)
                        WHERE b.sessionId NOT IN (SELECT remote_id FROM sessions)
                        """.trimIndent(),
                    )
                    db.execSQL(
                        """
                        DELETE FROM bookmarks
                        WHERE sessionId NOT IN (SELECT remote_id FROM sessions)
                        AND sessionId IN (SELECT CAST(id AS TEXT) FROM sessions)
                        """.trimIndent(),
                    )
                    db.rekey(
                        table = "sessions",
                        key = "remote_id",
                        columns =
                            "`remote_id` TEXT NOT NULL, `description` TEXT NOT NULL, `sessionFormat` TEXT NOT NULL, " +
                                "`sessionLevel` TEXT NOT NULL, `slug` TEXT NOT NULL, `title` TEXT NOT NULL, " +
                                "`endDateTime` TEXT NOT NULL, `endTime` TEXT NOT NULL, `isBookmarked` INTEGER NOT NULL, " +
                                "`isKeynote` INTEGER NOT NULL, `isServiceSession` INTEGER NOT NULL, `sessionImage` TEXT, " +
                                "`startDateTime` TEXT NOT NULL, `startTime` TEXT NOT NULL, `rooms` TEXT NOT NULL, " +
                                "`speakers` TEXT NOT NULL, `startTimestamp` INTEGER NOT NULL, " +
                                "`endTimeStamp` INTEGER NOT NULL, `sessionImageUrl` TEXT NOT NULL",
                    )
                    db.rekey(
                        table = "speakers",
                        key = "name",
                        columns =
                            "`name` TEXT NOT NULL, `tagline` TEXT NOT NULL, `bio` TEXT NOT NULL, " +
                                "`avatar` TEXT NOT NULL, `twitter` TEXT NOT NULL",
                    )
                    db.rekey(
                        table = "organizers",
                        key = "name",
                        columns =
                            "`name` TEXT NOT NULL, `tagline` TEXT NOT NULL, `link` TEXT NOT NULL, " +
                                "`type` TEXT NOT NULL, `photo` TEXT NOT NULL, `bio` TEXT NOT NULL, " +
                                "`twitterHandle` TEXT NOT NULL, `designation` TEXT NOT NULL, `createdAt` TEXT NOT NULL",
                    )
                    db.rekey(
                        table = "feed",
                        key = "title",
                        columns =
                            "`title` TEXT NOT NULL, `body` TEXT NOT NULL, `topic` TEXT NOT NULL, " +
                                "`url` TEXT NOT NULL, `image` TEXT, `createdAt` TEXT NOT NULL",
                    )
                }
            }

        /**
         * Every migration the database can perform. New migrations must be added here as
         * well as declared above; an unregistered migration is the same as none.
         */
        val ALL_MIGRATIONS: Array<Migration> = arrayOf(MIGRATION_4_5, MIGRATION_5_6)

        /** Rebuilds [table] with [key] as its primary key, keeping the newest row per key. */
        private fun SupportSQLiteDatabase.rekey(
            table: String,
            key: String,
            columns: String,
        ) {
            val names = Regex("`(\\w+)`").findAll(columns).map { it.groupValues[1] }.joinToString()
            execSQL("CREATE TABLE `${table}_new` ($columns, PRIMARY KEY(`$key`))")
            execSQL(
                "INSERT INTO `${table}_new` ($names) SELECT $names FROM `$table` " +
                    "WHERE id IN (SELECT MAX(id) FROM `$table` GROUP BY `$key`)",
            )
            execSQL("DROP TABLE `$table`")
            execSQL("ALTER TABLE `${table}_new` RENAME TO `$table`")
        }
    }
}